### ISSUE TITLE
Convert TypeReferences to TypeLiterals

### ISSUE THREAD

**Issue by carlo-quinonez** [BogdanMihaiciuc/ThingTransformer#4]
I'd like to be able to use regular TS interfaces to specify the type of function parameters. Currently, the transformer only allows using `TypeLiterals` when specifying a Type.

```ts
class UserUsageStatistics_Thing extends GenericThing {
  // ... some properties //
 
  public addStreamEntries({
    startDate,
    endDate,
    connectedUsers,
  }: {
    startDate?: Date;
    endDate?: Date;
    connectedUsers?: InfoTable<TF_GSS_ConnectedUser_DS>;
  } = {}): void {
    //... code goes here ...//
  }
}
```

I'd like to be able to use an interface here.

```ts
interface StreamEntry {
  startDate?: Date;
  endDate?: Date;
  connectedUsers?: InfoTable<TF_GSS_ConnectedUser_DS>;
}

class UserUsageStatistics_Thing extends GenericThing {
  // ... some properties //
 
  public addStreamEntries({
    startDate,
    endDate,
    connectedUsers,
  }: StreamEntry = {}): void {
    //... code goes here ...//
  }
}
```

The error is thrown at this [line](https://github.com/BogdanMihaiciuc/ThingTransformer/blob/024d85c5a6b1847a181b7d87cd83107aea472970/src/transformer/ThingTransformer.ts#L1271).

I've found a [blog post](https://levelup.gitconnected.com/writing-a-custom-typescript-ast-transformer-731e2b0b66e6) that mentions conversion of a `TypeReference` to `TypeLiteral`.

![image](https://user-images.githubusercontent.com/53790047/119012509-f55a8200-b94a-11eb-9d7a-6c63933ad6f5.png)

**Comment by BogdanMihaiciuc** [comment]
I will look into this

**Comment by BogdanMihaiciuc** [comment]
Should be fixed via https://github.com/BogdanMihaiciuc/ThingTransformer/commit/a2ad25a8de8071547d151e465916588551ca92cb

Make sure to upgrade your repo to transformer version 0.11 and also grab the updated build script to make use of it.
