### ISSUE TITLE
Invalid code emitted, input parameter undefined

### ISSUE THREAD

**Issue by stefan-lacatus** [BogdanMihaiciuc/ThingTransformer#58]
The following is a bug report for an issue that may be impossible to fix. Its goal is mostly to bring awareness in case someone else encounters it.

Given the following service:
```typescript
  TestCaseForBug({ test, letter }: { test: string; letter: string }): STRING {
    // initialize result with the value of the input param "letter"
    let result = letter;
    // iterate over the chars in 'test'. Can be replaced with
    // for (const letter of test) 
    for (let i = 0; i < test.length; i++) {
      // in this scope, redefine `letter`
      const letter = test[i];
      result += letter;
    }
    // result should be "letter" + "test"
    return result;
  }
```

When calling `TestCaseForBug({test: 'foo', letter: 'b'})`, the expected result would be `bfoo`. However, the method returns `undefinedfoo`.

While it could be said that the bug is caused by bad code style, it is valid code nonetheless. 

Why does it happen?

The emitted code is:
```javascript
var result = (function () {const METHOD_NAME = "TestCaseForBug";

    var result = letter;
    for (var i = 0; i < test.length; i++) {
        var letter = test[i];
        result += letter;
    }
    return result;
}).apply(me)
```

Because the transformer wraps the the code into an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE), and the fact that 'letter' is already declared in the outer scope, it will emit the same variable name `letter` inside the for loop.

**Comment by stefan-lacatus** [comment]
The behavior can be replicated in other javascript engines, by running the emitted code as such:

```javascript
var test = "foo";
var letter = "b";

var result = (function () {const METHOD_NAME = "TestCaseForBug";

    var result = letter;
    for (var i = 0; i < test.length; i++) {
        var letter = test[i];
        result += letter;
    }
    return result;
}).apply(me)

// prints 'undefinedfoo'
console.log(result);

**Comment by BogdanMihaiciuc** [comment]
This might actually be caused by the transformer stripping out the argument declaration entirely to prevent typescript from emitting the code to transpile the es6 destructuring syntax and might be fixable.
